// ============================================================
// Built-in audio + LED + haptic clips — header preserved as
// evidence of the firmware's asset-linking structure.
//
// Each #include below points to a C source/header pair that
// was auto-generated by `Tools/ModConverter/xrns2tt.py` from a
// Renoise `.xrns` song authored for the corresponding game
// event. The generated files contained the actual music, LED
// choreography, and haptic sequences played by the on-device
// synth and were linked statically into the firmware image.
//
// These generated files have been omitted from this portfolio
// publication, consistent with the policy applied to all other
// proprietary audio + creative assets of the product. See the
// repository LICENSE and Main/Feedbacks/README.md for context.
// ============================================================

#ifndef _POD_BUILTINCLIPS_H_
#define _POD_BUILTINCLIPS_H_

#include "BuiltinAssets/Mods/battery_alarm/src/battery_alarm.h"
#include "BuiltinAssets/Mods/charge_start/src/charge_start.h"
#include "BuiltinAssets/Mods/incubation_ar/src/incubation_ar.h"
#include "BuiltinAssets/Mods/incubation_complete/src/incubation_complete.h"
#include "BuiltinAssets/Mods/incubation_ongoing/src/incubation_ongoing.h"
#include "BuiltinAssets/Mods/receive_seed/src/receive_seed.h"
#include "BuiltinAssets/Mods/send_seed/src/send_seed.h"
#include "BuiltinAssets/Mods/send_seed_error/src/send_seed_error.h"
#include "BuiltinAssets/Mods/shake_incubation/src/shake_incubation.h"
#include "BuiltinAssets/Mods/shake_start/src/shake_start.h"
#include "BuiltinAssets/Mods/shake_start_error/src/shake_start_error.h"
#include "BuiltinAssets/Mods/shake_start_success/src/shake_start_success.h"

#endif